[package]
name = "oxide_cli"
version = "0.0.1"
edition = "2021"

[dependencies]
oxide_ipc = { workspace = true }
oxide_common = { workspace = true }
oxide_project = { workspace = true }

clap = { version = "4.5.8", features = ["derive"] }
structopt = { workspace = true }
